### ISSUE TITLE
Write Cypress tests for each endpoint as they're completed

### ISSUE THREAD

**Issue by BrendenMarks** [cs481-ekh/f22-fires-wild#111]
Once we understand all required endpoints, write tests validating the date returned for each one.
- [x] #158
- [x] Write tests for /variable_list endpoint (done in [#173](https://github.com/cs481-ekh/f22-fires-wild/issues/173))
- [x] #191
- [x] Write tests for /distinct_years_list endpoint (done in [#173](https://github.com/cs481-ekh/f22-fires-wild/issues/173))
- [x] Write tests for /distinct_counties_list endpoint (done in [#173](https://github.com/cs481-ekh/f22-fires-wild/issues/173))
- [x] #193

**Comment by collins-benjaminw** [comment]
closed as all stories are complete
