### ISSUE TITLE
Admin page startup/link-up to backend

### ISSUE THREAD

**Issue by samwise-311** [cs481-ekh/f22-fires-wild#161]
As a user, I want to be able to access the Admin page and its features, so that I can collect/manipulate the fire data.

## Definition of Done
- [x] Admin page on react links to django admin page
  - This is an env var, use process.env to link to the page so it works on deploy
  - Can hardcode but can't use process.env.REACT_APP_DJANGO_API_URL but cant use '//' to remove localhost:3000 because when I do the URL becomes: http// with no colon... WTF?? Without '//' it is localhost:3000/http://localhost:8000...
  - 3 hours
- [x] Document use of admin page in readme
- [x] Add credentials or space to add them in env variables

## Tasks
- [x] Task 1
- [x] Task 2
