### ISSUE TITLE
Add styling and custom colors to navbar in React app

### ISSUE THREAD

**Issue by samwise-311** [cs481-ekh/f22-fires-wild#163]
As a user, I want to have an attractive yet easy to navigate UI, so that I can focus on the larger functions of the website

## Definition of Done
- [x] Have a custom styled and fully functioning navbar and navbuttons on react frontend
- [x] Defined a consistent color scheme to be used throughout website frontend and its components

## Tasks
- [x] Come to a conclusion (and implement into navbar and other buttons )what color scheme will suit this website/team best.
- [x] Research/Implement package(s) to make appearance of navbar more attractive #182 
- [x] Research implementation of light/dark mode user option for front end #183 
- [x] Install and implement MUI #243 
- [x] Make sure all UI elements are consistent and user-friendly

**Comment by collins-benjaminw** [comment]
What do we think of adding research / work on light vs dark mode in this story?
