### ISSUE TITLE
Show variables from api request in dropdown

### ISSUE THREAD

**Issue by samwise-311** [cs481-ekh/f22-fires-wild#164]
Use the JSON data from the front end api request to populate the dropdowns so that user can select layers of map to view.

## Definition of Done
- [ ] A dropdown that lists all the available states from the list of states in dataset
- [ ] Dropdown changes a react-state or variable to get the latter dropdown(s) ready to populate

## Tasks
- [x] Populate a list with the list of states available from react axios data
- [x] #209
- [x] #211 
- [x] #213 
- [x] #215

**Comment by samwise-311** [comment]
Carried Over / Partially Implemented in Sprint 3
Did some reformatting and changed react package used.
State list is populating...but not rendering on dropdowns correctly.
