### ISSUE TITLE
Add descriptions and hover on variables

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#203]
As a user, I want to see descriptions of the variables, so that I can understand what to search on

## Definition of Done
- [x] variables api has descriptions of variables (validated from the sponsor)
- 15 minutes
- [x] Add and test Cypress test for testing descriptions from API
- 30 minutes
- [x] when hovering over the variable selectors in the data page, show tooltip with descripton
- Familiarize myself with frontedn code: 30 minutes
- Reasearch how to make an onHover box: 15 minutes
- Setup my frontend environment: 30 minutes
- Added Async function for variable list: 40 minutes
- Implement tooltips for year, state, and county (ended up hardcoding): 1 hours 30 minutes

## Tasks
- [x] Task 1
- [x] Task 2
