### ISSUE TITLE
Create details page & API for single fire

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#216]
As a user, I want to see all values of a fire, so that I can get information that I need

## Definition of Done
- [ ] When I click on a pindrop on a map, I get a link to a details page (/details/?ID=<primary-index-value-from-db>)
- [ ] When I click on the details link, I go to a page with a table that contains the name of each field and its value for that fire
- [ ] There should be a "about data" page accessible that has details of the variables, like the sponsor's excel sheet

## Tasks
- [ ] Task 1
- [ ] Task 2
