### ISSUE TITLE
link in modal to public excel of variable info

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#268]
As a user, I want to understand what the variables mean, so that I can understand the data

## Definition of Done
- [x] The sponsor has published a excel spreadsheet with public view link
- [x] on details modal, a link with target="_blank" directs users to spreadsheet in new tab

## Tasks
- [x] Email sponsor to publish public version of variable description sheet.
- [x] Add link from previous task to additional details page
