### ISSUE TITLE
deploy to sponsor's server

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#269]
As a [role], I want to [action], so that I can [goal]

## Definition of Done
- [ ] Sponsor's server running a version of our project with data deployed
- [ ] React in production mode on deployment
- [ ] Readme section with list of production deployment steps -> "deployment"

## Tasks
- [ ] Task 1
- [ ] Task 2
