### ISSUE TITLE
backend function to get sample selection of data

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#31]
depends on #28 , #27
To get the wildfire data to leaflet, we need a function that will return a sample of the data as a JSON object

- [x] function executes on a GET request of some kind to an endpoint in django backend #100 
- [x] get a sample of the wildfires from the database, at least name, latitude, longitude #99 
- [x] response as geojson (https://geojson.org/) #98
