### ISSUE TITLE
backend function to list unique values for non-numeric and non-datetime variables

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#39]
As a user, I want to get the possible values for filter variables, so that I can choose values to filter on 

## Definition of Done
- [x] Django API endpoint that lists FIRE_YEAR unique values
- [x] Django API endpoint that lists STATE unique values 
- [x] Django API endpoint that lists COUNTY unique values 
- [ ] Django API endpoint that lists county BY STATE unique values, this will require a state [parameter](https://www.django-rest-framework.org/api-guide/filtering/#filtering-against-query-parameters)

## Tasks
- [x] Task 1
- [x] Task 2
